### ISSUE TITLE
Question: Does the gem work with i.e. rails 5.2.pre?

### ISSUE THREAD

**Issue by dks17** [amatsuda/jb#18]
I encounted that rails render is not working with `jbuilder` in API mode.

```ruby
class ApplicationController < ActionController::API
end
class BooksController < ApplicationController
  def index
  end
end
```
```ruby
# views/books/index.json.jb
{author: {name: 'Matz'}}
```
Rails renders empty string with `jb` also like with `jbuilder`.
Does the gem work with rails 5.1 or 5.2.pre?

**Comment by esparratacus** [comment]
I looked up for this same issue in the Jbuilder project and found a quick fix for this.
https://github.com/rails/jbuilder/issues/346. just add
``ruby
class ApplicationController < ActionController::API
  include ActionView::Rendering
``

**Comment by dks17** [comment]
Thank you for the answer!
It seems I have already tried this quick fix. And now try this again and still get empty string with both `jb` and `jbuilder`.
```ruby
class ApplicationController < ActionController::API
  include ActionView::Rendering
end
```
After I reread about issue on link you gave and found [this comment](https://github.com/rails/jbuilder/issues/346#issuecomment-267748138):

> rspec does not render the views in controller tests by default

```ruby
RSpec.configure do |config|
  config.render_views = true
end
```
I was checking render with `rpsec` controller tests and `response.body` always return empty string `""`.
I checked it with `rails server` with browser and it works! Also I added the `rspec` setting and it also renders properly.

Now it works with both `jb` and `jbuilder`.

@esparratacus Thank you very much. You save my weekend.  :thumbsup:

In addition if someone needs it is possible to use both `jb` and `jbuilder` simultaneously:
```ruby
def index
  @books= Book.all
  render file: 'books/index.json.jbuilder'
end

show
  render 'show', formats: 'json', handlers: 'jb'
  # render 'show', formats: 'json', handlers: 'jbuilder'
end
```

**Comment by dks17** [comment]
The issue is solved.
