### ISSUE TITLE
Really cool name and awesome performance. BTW jb in chinese means dick.^_^

### ISSUE THREAD

**Issue by WalkPhoneGo** [amatsuda/jb#29]
Cooooooooooooooooooooooooooool!

JB = jiba = 鸡巴 = penis = 陰茎

And also jb is an adjective in chinese，which means awesome.

这个项目真JB好!!!!!!!!!!!!!!!!

This project is god damn awesome!!!!!!!!!!

I love this gem really!

**Comment by amatsuda** [comment]
@WalkPhoneGo Haha, thank you for letting me know this.
I'm not going to do anything (e.g. change the gem name, add documentation, etc) due to this "issue", so I'm just closing this.
