### ISSUE TITLE
Is editor syntax highlight support available on .jb?

### ISSUE THREAD

**Issue by KaitakuShiba** [amatsuda/jb#34]
I've searched for vscode extensions, such as `rails jb` or `jb`, but I can't seem to get any hits.
I would like to know if there are any extensions that jb extension support.
Thanks.

**Comment by aar0nr** [comment]
A `jb` template is just ruby, so you can configure your editor to use ruby syntax highlighting.

For vscode see: https://code.visualstudio.com/docs/languages/identifiers

```json
"files.associations": {
  "*.jb": "ruby"
}
```

**Comment by KaitakuShiba** [comment]
Thank you ! I think I can do this.
