### ISSUE TITLE
When partial returns nil, the result of `nil.to_s` is overwritten

### ISSUE THREAD

**Issue by Niyokee** [amatsuda/jb#44]
**how to reproduce**
1. prepare a partial template
2. the partial template returns `nil`

this is an example
```ruby
# foo.json.jb
{
  p: render(partial 'bar')
}

# _bar.json.jb
return if true
{
  age: 10,
  name: 'name'
}
```

**versions**
jb: 0.8.1
ruby: 3.2.2
rails: 7.1.1

I guess fb4b0de6c8b96b8b018cc623644a89a7b40faa96 has overwritten the NilClass object behavior.
Do you expect a partial to be implemented that return Hash or Array?

**Comment by amatsuda** [comment]
@Niyokee Thank you for reporting this!
> Do you expect a partial to be implemented that return Hash or Array?

While I would answer "yes" to this question, a template engine should of course never change `nil` object's behavior anyway. I made a fix on af5997e808c11ed06e56f393c2f562009e2ed57b and published a new release versioned 0.8.2 with this fix.

Thanks!
